allow-insecure-host = ["mirrors.tuna.tsinghua.edu.cn", "mirrors.aliyun.com"]
# index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
index-url = "http://mirrors.aliyun.com/pypi/simple"
extra-index-url = []
native-tls = true
